typography_spectrum: 0.9822154145222157
color:
  brandColors:
    - '#0C0B1B'
    - '#E8E7E5'
    - '#797A83'
    - '#494955'
    - '#E86A64'
  brandStrength: 0.24568953388370574
  lightness: 0.9124039155431092
  saturation: 0.6268192785792053
  rhythmicContrast: 0.7398073002696037
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.11236664652824402
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Pascal Hiel
  email: Pascal@balefirehq.com
  url: www.balefirehq.com
name: TESLA
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Tesla S III X
    id: c6056a05-36f1-4753-99d3-4663747c5452
    type: content
  - name: Tesla Powerwall
    id: 342060c7-1ede-428f-baae-02f29423a298
    type: content
favicon: null
title: Tesla Art en Movies
purpose: []
