typography_spectrum: 0.6300885311793536
color:
  brandColors:
    - '#b59d86'
    - '#2e3846'
    - '#555c60'
    - '#0b0907'
    - '#d4c8c6'
  brandStrength: 0.4971108930185437
  lightness: 0.9013178679160774
  saturation: 0.6866892264224589
  rhythmicContrast: 0.01670681918039918
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Pascal Hiel
  email: Pascal@balefirehq.com
  url: www.balefirehq.com
name: TeslaClips
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Tesla Art en Movies
purpose: []
