name: TeslaClips
favicon: null
layout_spectrum: 0.48522408376447856
typography_spectrum: 0.6300885311793536
title: Tesla Art en Movies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b59d86'
    - '#2e3846'
    - '#555c60'
    - '#0b0907'
    - '#d4c8c6'
  brandStrength: 0.4971108930185437
  lightness: 0.9013178679160774
  saturation: 0.6866892264224589
  rhythmicContrast: 0.01670681918039918
purpose: []
